[package]
name = "rust-python-ndarray-tutorial"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/rust/lib.rs"


[dependencies]
itertools = "0.11.0"
ndarray = { version = "0.15.6", features = ["rayon", "approx"] }

[dev-dependencies]
ndarray-npy = "0.8.1"
tracing = "0.1.37"
